name: Docker Image CI

on: [push]

jobs:
  build:
    name: Build ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [
          "phoenix:latest",
          "cmake:3.11.3",
          "boost:1.67.0",
          "clang:6.0"
        ]

    steps:
    - uses: actions/checkout@v1
    - name: Docker build
      run: docker build ./${{ matrix.image }} --tag ${{ matrix.image }}
